Fix error message when method does not exist in JVM
Changes error message from:
Py4JError: py4j.examples.ExampleClassgetField1 does not exist in the JVM
to:
Py4JError: py4j.examples.ExampleClass.getField1 does not exist in the JVM