Upgrade Sphinx requirement for documentation build (#535)
This PR proposes to upgrade Sphinx version to fix up the documentation build. It fails as below:

```
Run cd py4j-web && make clean html && cd ..
rm -rf _build/*
sphinx-build -b html -d _build/doctrees  "-W" . _build/html
Running Sphinx v4.5.0

Sphinx version error:
The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
make: *** [Makefile:33: html] Error 2
mv: cannot stat 'py4j-web/_build/html': No such file or directory
Error: Process completed with exit code 1.
```

for now, see also https://github.com/py4j/py4j/actions/runs/8228399854/job/22497777089?pr=519